var files =
[
    [ "avr_compiler.h", "avr__compiler_8h.html", "avr__compiler_8h" ],
    [ "classb_analog.c", "classb__analog_8c.html", "classb__analog_8c" ],
    [ "classb_analog.h", "classb__analog_8h.html", "classb__analog_8h" ],
    [ "classb_cpu.h", "classb__cpu_8h.html", "classb__cpu_8h" ],
    [ "classb_cpu_gcc.c", "classb__cpu__gcc_8c.html", "classb__cpu__gcc_8c" ],
    [ "classb_cpu_iar.c", "classb__cpu__iar_8c.html", null ],
    [ "classb_crc.h", "classb__crc_8h.html", "classb__crc_8h" ],
    [ "classb_crc_hw.c", "classb__crc__hw_8c.html", "classb__crc__hw_8c" ],
    [ "classb_crc_hw.h", "classb__crc__hw_8h.html", "classb__crc__hw_8h" ],
    [ "classb_crc_sw.c", "classb__crc__sw_8c.html", "classb__crc__sw_8c" ],
    [ "classb_crc_sw.h", "classb__crc__sw_8h.html", "classb__crc__sw_8h" ],
    [ "classb_freq.c", "classb__freq_8c.html", "classb__freq_8c" ],
    [ "classb_freq.h", "classb__freq_8h.html", "classb__freq_8h" ],
    [ "classb_interrupt_monitor.c", "classb__interrupt__monitor_8c.html", "classb__interrupt__monitor_8c" ],
    [ "classb_interrupt_monitor.h", "classb__interrupt__monitor_8h.html", "classb__interrupt__monitor_8h" ],
    [ "classb_rtc_common.c", "classb__rtc__common_8c.html", "classb__rtc__common_8c" ],
    [ "classb_rtc_common.h", "classb__rtc__common_8h.html", "classb__rtc__common_8h" ],
    [ "classb_sram.c", "classb__sram_8c.html", "classb__sram_8c" ],
    [ "classb_sram.h", "classb__sram_8h.html", "classb__sram_8h" ],
    [ "classb_wdt_test.c", "classb__wdt__test_8c.html", "classb__wdt__test_8c" ],
    [ "classb_wdt_test.h", "classb__wdt__test_8h.html", "classb__wdt__test_8h" ],
    [ "error_handler.h", "error__handler_8h.html", "error__handler_8h" ],
    [ "analog/UserApplication.c", "analog_2_user_application_8c.html", "analog_2_user_application_8c" ],
    [ "crc/UserApplication.c", "crc_2_user_application_8c.html", "crc_2_user_application_8c" ],
    [ "frequency/UserApplication.c", "frequency_2_user_application_8c.html", "frequency_2_user_application_8c" ],
    [ "interrupts/UserApplication.c", "interrupts_2_user_application_8c.html", "interrupts_2_user_application_8c" ],
    [ "registers/UserApplication.c", "registers_2_user_application_8c.html", "registers_2_user_application_8c" ],
    [ "sram/UserApplication.c", "sram_2_user_application_8c.html", "sram_2_user_application_8c" ],
    [ "wdt/UserApplication.c", "wdt_2_user_application_8c.html", "wdt_2_user_application_8c" ]
];